### PR TITLE
CI: enable windows builds

### PR DESCRIPTION
**Pull request by fzzr-**
Fix builds for windows
- [x] Tests (ci.yml) 
- [x] Release (release-tools.yml)

### CODE REVIEW

**Comment by cab404** [comment]
rebased everything, unified lib installation on all platforms, added lib reuse and added clippy as a bonus :D

**Comment by cab404** [comment]
@fzzr- imo we can merge this, and I will refactor the rest in a separate commit.
or I can just change the title of this one to be more general

**Comment by fzzr-** [comment]
Unfortunately not yet because releases for windows are broken probably. Look at [release-tools](https://github.com/pontem-network/move-tools/pull/31/files#diff-7e593009d3235559d2a215754f156e4464ad38c4d133455e8e7e37a8247025f1R45-R46).

**Comment by cab404** [comment]
So, I've tried to make a release matrix for building everything release-related in a super-parallel ultrasonic mega-magical way.

Unfortunately, I've noticed a bit late (3h+ into doing arch for excluding builds from matrix, rejoining built artifacts from multiple machines, etc.) that probably I shouldn't optimize prematurely. 
_otherwise I would've probably spent another day or two making a beautiful parallel build graph, which would save us upwards to 10 minutes per release (!!! :D)_

So, I've popped openssl installation right into tools build script and gotta go get some sleep. I can't really imagine a way it can break release builds if they already had worked.

Speaking of "if they already had worked": [what does that mean?](https://github.com/pontem-network/move-tools/blob/4e62c9603743c836bb169638dbf52123733649f9/.github/workflows/release-tools.yml#L4) Like, I can't imagine that intent was to create an array with words "Create" "Release" "Page". Is that something we should touch as part of fixing stuff?

**Comment by cab404** [comment]
Oh, and per-commit tests now should run 2.5-3 times more quickly.

**Comment by cab404** [comment]
Seems a bit hackish, but should be totally fine)

**Comment by cab404** [comment]
@fzzr- plz review

**Review by fzzr- — COMMENTED** [review]
LGTM 👍 Thanks!

**Pull request merged**
